#pragma once

enum UboBindPoint : int32_t {
  BINDING_UBO_CAMERA,
};

enum SsboBindPoint : int32_t {
  BINDING_SSBO_INSTANCES,
  BINDING_SSBO_DIRECTIONAL_LIGHTS,
  BINDING_SSBO_POINT_LIGHTS,
  BINDING_SSBO_SPOTLIGHTS,
};

enum SamplerBindPoint : int32_t {
  BINDING_SAMPLER_SCREEN,
  BINDING_SAMPLER_DIFFUSE = 0,
  BINDING_SAMPLER_DIFFUSE_OVERLAY,
  BINDING_SAMPLER_SPECULAR,
  BINDING_SAMPLER_EMISSION,
  BINDING_SAMPLER_ENVIRONMENT,
  BINDING_SAMPLER_DIRECTIONAL_SHADOWS,
  BINDING_SAMPLER_POINT_SHADOWS,
  BINDING_SAMPLER_SPOTLIGHT_SHADOWS,
};
